baseurl = "https://softwareinblue.com/"
#baseurl = "http://softwareinblue.com.s3-website.us-east-2.amazonaws.com/"
languageCode = "en-us"
title = "Can I get that software in blue?"
theme = "castanet"
googleAnalytics = "G-WLVZ4G6NNM"
themesDir = "./themes"
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[params]
mainSections = ["episode"]
#episode_number_style  = "brackets"
#episode_number_prefix = "CWC"
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "Copyright 2021 [Can I get that software in blue?](https://softwareinblue.com)"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/can-i-get-that-software-in-blue/id1561899125?ign-mpt=uo%3D4&mt=2"
android_subscribe = "https://subscribeonandroid.com/softwareinblue.com/anchor_podtrac_rss.xml"
spotify_subscribe = "https://open.spotify.com/show/25r9ckggqIv6rGU8ca0WP2"
google_play_subscribe = "https://podcasts.google.com/feed/aHR0cHM6Ly9zb2Z0d2FyZWluYmx1ZS5jb20vYW5jaG9yX3BvZHRyYWNfcnNzLnhtbA"
stitcher_subscribe = "https://www.stitcher.com/podcast/can-i-get-that-software-in-blue"
#soundcloud_subscribe = ""
#pocketcasts_subscribe = ""
#mailchimp_subscribe = ""
rss_subscribe = "https://softwareinblue.com/anchor_podtrac_rss.xml" #only set this if you don't want to use the built-in feed
description = "Can I get that software in blue? is a hot-air balloon ride exploring the whimsy and caprice of enterprise software marchitecture sales hosted by the world’s foremost aeronauts."
media_prefix = ""
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2021 Can I get that software in blue" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Podcast by presales for presales" #no markdown or HTML
    itunes_author = "softwareinblue" #no markdown or HTML
    itunes_summary = "Can I get that software in blue?, a podcast by and for people engaged in technology sales. If you are in the technology presales, sales, support or professional services career paths then this show is for you!  Your hosts Steve Mayzak and Chad Tindel will take you on a hot-air balloon ride exploring the whimsy and caprice of enterprise software marchitecture sales."# Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Chad Tindel"
    itunes_owner_email = "chad@softwareinblue.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://is3-ssl.mzstatic.com/image/thumb/Podcasts114/v4/87/b4/01/87b401ab-8a5a-2819-2d1c-a8a1a017b3b6/mza_12162978830911181992.jpg/313x0w.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

#  [params.podlove] # https://subscribe-button.podlove.org
#    subscribe_title = ""              # fallback: site title from above
#    subscribe_subtitle = ""           # fallback: ""
#    subscribe_description = ""        # fallback: ""
#    subscribe_cover = "img/logo.jpg"  # fallback: ""
#    subscribe_color = "#585e6c"       # fallback: ""
#    subscribe_size = "medium"         # options: small, medium, big
#    subscribe_format = "rectangle"    # options: rectangle, square, cover
#    subscribe_style = "filled"        # options: filled, outline, frameless
#    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#    subscribe_feed_type = "audio"     # options: audio, video
#    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    #github = ""
    #gitlab = ""
    #facebook = ""
    #facebook_admin = [] # This needs to be one or more page admins to get domain insights
    twitter = "softwareinblue"
    twitter_domain = "softwareinblue.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    #googleplus = ""
    #pinterest = ""
    #instagram = ""
    youtube = "channel/UC8qfPUKO_rPmtvuB4nV87rg"
    linkedin = "https://linkedin.com/company/softwareinblue/"
    twitch = "softwareinblue"

  [params.authors]
    [params.authors.stevemayzak]
      name	= "Steve Mayzak"
      thumbnail = "img/host/stevemayzak.jpg"
      bio = "Steve Mayzak is Vice President, Global Solution Engineering at Grafana Labs.  He is a builder of pre-sales teams having previously built the Solution Architect team at Elastic, Inc. from the ground up until post-IPO and is now working on doing the same thing at Grafana Labs."
      [params.authors.stevemayzak.social]
        github = ""
        facebook = ""
        twitter = "smayzak"
        linkedin = "stevemayzak"
        homepage = ""
        pinterest = ""
        instagram = ""
        youtube = ""
        twitch = ""
    [params.authors.chadtindel]
      name	= "Chad Tindel"
      thumbnail = "img/host/chadtindel.png"
      bio = "Chad Tindel is a Principal NoSQL Solution Architect at Amazon Web Services.  He holds a BS in Computer Science from the Cal Poly SLO as well as an MBA and MS Finance from the University of Denver.  After 12 years of writing code professionally, Chad discovered that he really loved working with customers and has since worked at a slate of very successful companies as a Solution Architect: Red Hat, Cloudera, MongoDB, Prevoty, Elastic, and AWS."
      [params.authors.chadtindel.social]
        github = ""
        facebook = ""
        twitter = "ctindel"
        linkedin = "ctindel"
        homepage = ""
        pinterest = ""
        instagram = ""
        youtube = ""
        twitch = ""

#    [params.links]
#      [params.links.ado]
#        name = "Arrested DevOps"
#        url = "https://www.arresteddevops.com"
#      [params.links.ffs]
#        name = "Food Fight Show"
#        url = "https://foodfightshow.org"
#      [params.links.sdt]
#        name = "Software Defined Talk"
#        url = "https://cote.io/podcasts/sdt/"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "aws"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://softwareinblue.com?region=us-east-2"
# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E3IAJ0V7VO9VOJ"
#exclude = "^.+(anchor_podtrac_rss.xml|sib_rss.xml)"
#exclude = "/sib_rss.xml"
exclude = "*rss*.xml"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
